version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - model_cache:/root/.cache/huggingface
    command: python main.py
    deploy:
      resources:
        limits:
          cpus: '3.0'
volumes:
  model_cache:
